routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('index');
// });
Route::get('/', 'IndexController@index');
Route::get('/proxy', 'IndexController@proxy');
Route::get('/fetchUrl', 'IndexController@fetchUrl');
Auth::routes();

Route::resource('posts', 'PostsController');

Route::resource('map', 'MapController');
// manager
Route::resource('manager', 'ManagerController');

// get post draw data
Route::get('/data/posts/{id}', 'PostsController@get_posts_body');
Route::post('/upload', 'PostsController@upload');

Route::get('/test', function () {
    return File::get(public_path() . '/test.html');
});

//# sitemap
Route::get('/sitemap.xml', 'SitemapController@Index');

//# Protfolio
Route::get('/portfolio', 'ProtfolioController@Index');
Route::get('/portfolio/wind', 'ProtfolioController@Wind');
Route::get('/portfolio/roadmap', 'ProtfolioController@Roadmap');
Route::get('/portfolio/jargon', 'ProtfolioController@jargon');

resources/views/inc/messages.blade.php
@if(count($errors) > 0)
    @foreach($errors->all() as $error)
        <div class="alert alert-danger p-10">{{$error}}</div>
    @endforeach
@endif 

@if(session('success'))
    <div class="alert alert-success p-10">
        {{session('success')}}
    </div>
@endif

@if(session('error'))
    <div class="alert alert-danger p-10">
        {{session('error')}} 
    </div>
@endif

resources/views/inc/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-xs">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            re<span class="font-medium" style="color:#00bcd4;">x</span>code
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

                <li class="nav-item ">
                    <a class="nav-link" href="/posts?f=IT">IT</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="/posts?f=snippet">Snippet</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="/posts?f=other">雜</a>
                </li>

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <!--<li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>-->
                    @if (Route::has('register'))
                        <!--<li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>-->
                    @endif
                @else
                    <li class="nav-item dropdown">

                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                            <a href="{{ route('posts.create') }}" class="dropdown-item">Create post</a>
                            <a href="/manager" class="dropdown-item">管理頁</a>
                            <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                  document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>